$ANSIBLE_VAULT;1.1;AES256
38363164316335626463386566626162323962646462653634323864366161616664613637396635
3533666264626264313138643133663866333866373866630a356562343262613439613064343134
35376634626462643361666663613463323131373361393235356162333932663837623665353239
3361383232616433350a333666313931333030643031383365393762333864373963623731336332
3166
