$ANSIBLE_VAULT;1.1;AES256
66646338326335656165643062306437326663653665373534623039376133343830376564646363
3931346131663761323466393239626664313330613036310a633331393435343639373436613535
34306334303736383266303261353435336235333163343231386663343064303765353163663732
6464373663633366660a313666353333356565326361653762333536323331356337616461636235
6464
